### ISSUE TITLE
Reducing issue filling by using an external communication platform

### ISSUE THREAD

**Issue by dnamsons** [dylanbeattie/rockstar#100]
[Gitter](https://gitter.im/) and [keybase](https://keybase.io/) are good options. This would make talking about ideas more streamlined.

**Comment by cwfitzgerald** [comment]
I strongly +1 gitter.

**Comment by young-steveo** [comment]
There's a [subreddit](https://www.reddit.com/r/RockstarDevs/)

**Comment by cwfitzgerald** [comment]
There is, but I feel like it has the same issue that the issues have, it is inherently thread based. It would be good to also have a chat based form of communication so we can easily discuss random things without the formality of a thread.

**Comment by gunnerwolf** [comment]
Why not create a [Discord](https://discord.gg) server? It's convenient not only for direct chatting and communication, but for storing plans, making announcements etc

**Comment by gunnerwolf** [comment]
Just created one.
[Here's the invite link](https://discord.gg/xsQK7UU)

I'll go through putting up some info and setting up some basic roles in a few hours once I'm home.

**Comment by cwfitzgerald** [comment]
Yeah I'm doing this! Let's all get on there :)

**Comment by xzinik** [comment]
discord to me looks like a good place to discuss thing about rockstar without being too topic oriented
