### ISSUE TITLE
Add spec for boolean operators (and/or)

### ISSUE THREAD

**Issue by wolfgang42** [dylanbeattie/rockstar#101]
They're being used in the examples, but they're not in the spec yet.

Operator precedence should also be specified. Based on the examples, `and` definitely binds outside of function calls, but I can't really tell beyond that.

**Comment by palfrey** [comment]
Also that `is` binds more strongly than `and` as 
`Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing`
seems to read as
`(Midnight taking my world, Fire is nothing) and (Midnight taking my world, Hate is nothing)`

**Comment by cwfitzgerald** [comment]
This should be solved by my WIP spec in #97.
