### ISSUE TITLE
Function syntax for functions with 0 arguments is not defined

### ISSUE THREAD

**Issue by scizor666** [dylanbeattie/rockstar#102]

**Comment by cwfitzgerald** [comment]
I want the opinions of the other implementers, but I think always passing `nothing` as an argument and a variable name would work.

```
Funky Stuff takes Nothing
Uptown's Funk you up
Give back Uptown

Scream Funky Stuff taking nothing
```

**Comment by wolfgang42** [comment]
wolfgang42/rockstar-js currently takes the JS semantics (i. e. don't care if the arguments match or not; ignore if too many and put `mysterious` if too few) but I agree that passing Nothing for 0-argument functions seems reasonable.

**Comment by young-steveo** [comment]
@cwfitzgerald's suggestion `takes nothing` makes sense and is idiomatic.

**Comment by cwfitzgerald** [comment]
@young-steveo note that it is `taking Nothing` with a capital N, making it just a normal variable declaration.

**Comment by young-steveo** [comment]
@cwfitzgerald I dunno, `taking nothing` lowercase insinuates `null` which works too.

**Comment by cwfitzgerald** [comment]
My goal was to allow this to be a convention thing, while keeping the parsers identical.
