### ISSUE TITLE
maybe reconsider the pronouns

### ISSUE THREAD

**Issue by mbutterick** [dylanbeattie/rockstar#104]
> The keywords it, he, she, him, her, they, them, ze, hir, zie, zir, xe, xem, ve, and ver refer to the last named variable determined by parsing order.

1. The “last named variable” requirement is a knotty complication in terms of parsing & interpreting `rockstar`.  Perhaps make `he`/`him`, `she`/`her` etc into aliases for a set of underlying `him` / `her` / etc variables (in the same way that `wrong` `no` and `lies` are aliases for `true`)

2. The apparent omission of `I`/`me`/`my` and `you`/`your` seems like a rather large gap in the spec, but could be handled consistent with the pattern above.

**Comment by ep12** [comment]
my etc. are keywords for common variables like `my world`

**Comment by cwfitzgerald** [comment]
I don't really think it's that much of a complication. I would be interested to see what is making it difficult. Once you generate an AST, walk the AST in source first order, keeping a record of the last variable that was used, Replace all pronouns with the last variable used. That is how I will implement it in the webpiler once it's implemented.

**Comment by wolfgang42** [comment]
I agree with @cwfitzgerald, pronouns are easy to implement by walking the AST after parsing to do a replace step. This is what I'm doing in rockstar-js.
