### ISSUE TITLE
Truthy values

### ISSUE THREAD

**Issue by palfrey** [dylanbeattie/rockstar#107]
The "Conditionals" section says `If the expression evaluates to true` but doesn't define what's "true". In many languages, there's a "truthy" set of values and everything else is "false" (or vice-versa depending on the whims of the language designers). Any thoughts?

(Ran into this in #105 which worked because in the Python interpreter "0" was treated as a boolean value)

**Comment by cwfitzgerald** [comment]
I'm going to try to wrap this into #97 so we have a single proposal for how types work, I'm going to follow up there.
