### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by palfrey** [dylanbeattie/rockstar#108]
cellular-rocktomata (#105) relies on being able to do string concatenation with the `plus`/`with` operator, which currently isn't part of the spec, but I'm not seeing any other way to do this currently. Can this be added? Similarly `times` with "&lt;string&gt; `times` &lt;integer&gt;" might be of use.

**Comment by cwfitzgerald** [comment]
#97 covers this with implicit conversions. I will update the list there momentarily to provide definitions for all operators.
