### ISSUE TITLE
around we go

### ISSUE THREAD

**Issue by ep12** [dylanbeattie/rockstar#11]
In the example
```
Tommy was a dancer
While Tommy ain't nothing,
Knock down Tommy
And around we go
```
the usage/effect of `around we go` is unclear. It could be an alias for continue. But it is definitely not needed because any line that doesn't start with And ends the block. For a parser this could be difficult if the file doesn't end with a newline, don't forget to clean up opened blocks or throw an error (unexpected EOF) if you write a parser

**Comment by peteri** [comment]
Currently makes most sense if it's an alias for "end", and I think while and until should require an end statement.

**Comment by peteri** [comment]
Hmm but I like around we go. although I am wonder if "chorus" could be used somewhere.
Currently bashing together a tokeniser / parser and so far this is only really painful bit, all though And could be a bit of a nuisance.
Also I think a language called Rockstar should be unimplementable with standard lex/yacc.
