### ISSUE TITLE
Variable scope

### ISSUE THREAD

**Issue by palfrey** [dylanbeattie/rockstar#111]
There's nothing in the current spec detailing scope for variables, although it seems to indicate they're mostly pure functions i.e. no setting of global variables except at top-level; only change to the outer scope's variables is the function's return value.

**Comment by cwfitzgerald** [comment]
I think we should go with similar scoping rules to python. You may use global variables wherever you want to, but if you want to write to it, you have to bring it into scope with something like `Get <variable> in here!`

**Comment by young-steveo** [comment]
As a developer scope is important for organization, but as a lyricist if I define `Tommy is a badass` then `Tommy` should equal `16` pretty much everywhere in the song unless I `Build Tommy up` or `Knock Tommy down`.

Trying to explain that `Tommy` in the bridge (local scope) is not the same as `Tommy` in the verse (global scope) makes the Rockstar lyrics cumbersome, I think..

**Comment by cwfitzgerald** [comment]
I think we're talking about the differences between being within and outside of a function, so that may not cause that much of an issue, this is more for ease of development than anything.

**Comment by dancxjo** [comment]
I'm trying to program a recursive Fibonacci generator, but since I can't use local variables, I don't think recursion is possible. :(

I agree with the above point that multiple Tommies seem weird in natural language. I would propose that one of the determiners used to make common variables be repurposed...like `my` (for a cute throwback to Perl).

**Comment by gunnerwolf** [comment]
I think from a development point of view, local scope is an important feature, and from a lyrical point of view, `Tommy is a badass` is not defining Tommy as 16, but as a badass. So he could later also be defined as a moron, and it would be lyrically sound, as one can be a badass moron (albeit quite rare)

**Comment by cwfitzgerald** [comment]
I think that this is one of those situations where we need to give priority to programming over lyricism. Lyrics are allowed to make little sense (up for "interpretation") but programs have to make sense. If we didn't have local variables that would be extremely difficult to do...anything at all. Global state is a recipe for disaster (just take a look at any language's recommended style --- it will recommend against as much global state as possible). I still stand by my opinion that scoping rules should be like python's, with something to allow you to write to global state if need be.

Also what implementation doesn't support local functions and recursion?
