### ISSUE TITLE
MIME-Type

### ISSUE THREAD

**Issue by cwfitzgerald** [dylanbeattie/rockstar#114]
As I am setting up various things in the webpiler, I have code going back and forth that is currently MIME-Type-less, should we change that?

**Comment by gunnerwolf** [comment]
`application/rockstar`?

**Comment by xzinik** [comment]
i support the application/rockstar but i cant stop thinking that it should be something like application/track or application/song or something along the line of this like /playlist /lyrics /disc  because to me it reminds of music, but they are not as concise as application/rockstar

**Comment by cwfitzgerald** [comment]
I would love something like that too, but I would have to agree, application/rockstar. I should make a PR.

**Comment by wolfgang42** [comment]
Please bear in mind that media types are registered with IANA! We should not make one up without registering it properly.

I do not have any experience with this process myself but it seems that 'standards tree' types such as `application/rockstar` must have an actual ratified standard such as an RFC. The "vanity" tree ("for media types created experimentally") would seem to be the most appropriate for the present state of rockstar; though this still requires registration it seems relatively trivial to obtain one in this tree.

I suggest that if there is any pressing need for a media type, one in the unregistered tree should be used for the moment, such as `application/x.rockstar`. Once development of the spec has settled somewhat we can look into registering an official type. ([RFC 6838](https://tools.ietf.org/html/rfc6838) notes that unregistered types are intended for use between actively agreeing parties and strongly discourages their use, but I think that for the immediate present they are an appropriate solution.)

I also wonder about `text/` vs `application/`. Clearly Rockstar programs are text files, but I am not sure what the present advice is on which type to use. For example, JS is both `text/javascript` and `application/javascript`; I don't know if there is a standard which specifies a preference for one over the other.

**Comment by cwfitzgerald** [comment]
Color me surprised. I always thought the mime-type thing was "there are standards for the big ones, but label them as necessary". I think `application/x.rockstar` is a perfectly viable solution.

**Comment by cwfitzgerald** [comment]
Closing this because it's frankly not really necessary, and x.rockstar is fine for now.
