### ISSUE TITLE
Decrementing multiple times in a row

### ISSUE THREAD

**Issue by TessFerrandez** [dylanbeattie/rockstar#123]
Suggestion: allow using down multiple times in a row to decrement variables multiple steps 

Knocking down, down, down 

Also, suggest allowing “going down” as an alternative to knocking down as in the following example 

I'm going down
I'm going, down, down, down
Down, down
Yes, I'm going down, yes
I'm going down, down, down
Down, down

Same should apply to up

**Comment by cwfitzgerald** [comment]
I support this whole heartedly. I think may others will as well.

**Comment by dylanbeattie** [comment]
Great idea.

**Comment by cwfitzgerald** [comment]
I'll write up a PR for this when I get a chance tomorrow (unless someone beats me to it) :)
