### ISSUE TITLE
Examples of poetic number literals that seem to start with a keyword

### ISSUE THREAD

**Issue by wicknera** [dylanbeattie/rockstar#132]
I hope this has not been covered before since there already were a couple of discussions about keywords in poetic number literals, but my own implementation stumbles about an apparent ambiguity in the language specification:

- The definition of _poetic number literals_ states that "**As long as the next symbol is not a reserved keyword**, the rest of the line is treated as a decimal number"
- The definition of _common variables_ states that "Common variables consist of one of the **keywords a**, an, the, my or your followed by a unique variable name"

I interpret this to mean that "a" is a keyword and that therefore "a" can not start the numeric values of a poetic number literal. However, the specification contains examples such as...

- "Sweet Lucy was a dancer"

...which in this interpretation would not be considered valid.
I hope that there is no difference between "keywords" and "reserved keywords"?

**Comment by cwfitzgerald** [comment]
This is a dupe of #112, solved by #117. You have any "Reserved Keywords" in a poetic number literal,but they may not start with a "literal word" such as "nothing" or "mysterious". 
---
Connor Fitzgerald

**Comment by wicknera** [comment]
This does not make life for implementers a lot easier, but you are certainly right that this fixes the specification. Thank you!

**Comment by cwfitzgerald** [comment]
It doesn't, but there are quite a few pieces of ambiguity that have come up that I'm attempting to stomp out with #117 and #131. I think both will merge in with minimal changes, so imo you should take them as part of the standard.
