### ISSUE TITLE
Poetic type literals missing aliases in spec

### ISSUE THREAD

**Issue by wizered67** [dylanbeattie/rockstar#138]
In the spec, poetic type literal assignment says that `For the keywords true, false, nothing, nobody and nowhere, a poetic assignment is a single line consisting of a variable name, the is keyword and the required value literal`. It seems arbitrary that these keywords work, but the other aliases for these keywords don't work. The spec doesn't even list "null" as an acceptable value which seems a bit surprising. Unless people see reason otherwise, I think it would make sense for poetic assignment for type literals to accept any alias of true, false, and null, as well as possibly mysterious which is currently unmentioned.

**Comment by cwfitzgerald** [comment]
This is fixed by #117 by completely rewording that section.

**Comment by wizered67** [comment]
Ah sorry, must have missed that. Thanks!
