### ISSUE TITLE
Announcing the Enterprise™ lang

### ISSUE THREAD

**Issue by joaomilho** [dylanbeattie/rockstar#141]
The world is not made only of Rockstar programmers. For all the non hipsters out there, now there's Enterprise™ https://github.com/joaomilho/Enterprise. For now there's a working Web3.0 implementation that compiles to well-known web technologies like JScript, JavaScript and Ajax.

Let it be known.

**Comment by dylanbeattie** [comment]
Added link to the README: https://github.com/dylanbeattie/rockstar/commit/f361b4f5ebf95a831f2a5ea03cfad26ca21ac563
