### ISSUE TITLE
example: "My world is nothing without..." is misleading

### ISSUE THREAD

**Issue by a-ruzin** [dylanbeattie/rockstar#149]
Documentation states:
```
My world is nothing without your love - Initialize my world with the result of subtracting your love from 
0
```
But this is WRONG!

We should initialize ```My world``` with ```Your love``` not ```-Your love```.
```Is``` in this context should be interpreted as a part of equation, which compiler should solve.

Good luck Rockstar developers! ;)

**Comment by marcinruszkiewicz** [comment]
Yep. #128 deals with that (also see the other issues/PR's linked to it)

**Comment by dylanbeattie** [comment]
Moved into https://github.com/dylanbeattie/rockstar/issues/158
