### ISSUE TITLE
Strings must use double quotes

### ISSUE THREAD

**Issue by Dentosal** [dylanbeattie/rockstar#16]
If single-quoted strings are allowed, words like `isn't` and `doesn't` become harder to parse. Even worse, `wakin'` and `'bout` are impossible.

**Comment by simcop2387** [comment]
I think we should still allow another quoting method to make the use of " inside strings more ergonomic.  How about using 🎶 or one of the other notes?  🎜 🎝 ♩ ♪ ♫ ♬

**Comment by dylanbeattie** [comment]
This is a very good point. After all, we want to be able to parse `I ain't talkin' 'bout love` as a set of identifiers...
