### ISSUE TITLE
"taking" is reserved - example mismatch?

### ISSUE THREAD

**Issue by dieswaytoofast** [dylanbeattie/rockstar#17]
You've got

> `My dreams were ice. A life unfulfilled; wakin' everybody up, taking booze and pills` - initialises my dreams with the value `3.1415926535'

Isn't `taking` a reserved keyword here? Or does that not count during assignments?

**Comment by edmund-h** [comment]
I noticed this as well...

**Comment by dylanbeattie** [comment]
Given that a poetic literal explicitly captures everything up to the end of the line, I see no reason why you can't use reserved keywords within the literal itself, so this is probably OK. I'll add a note to that effect.
