### ISSUE TITLE
Aliases for true and false

### ISSUE THREAD

**Issue by aRTy42** [dylanbeattie/rockstar#19]
I would suggest `right`, `wrong`, `eternal` and `a lie`.

**Comment by unrelatedlabs** [comment]
+ ok, sure, no way, rock, lame

**Comment by MethodZero** [comment]
`real`, `a facade`, `forever`, `an illusion`

**Comment by dylanbeattie** [comment]
https://github.com/dylanbeattie/rockstar/commit/285f17193144513b2ad67fe9b6b66b2ea6ddb1b9 adds aliases for `right`, `wrong`, `yes`, `no`, `lies` and `ok`

I quite like 'a facade' and 'an illusion', but these are probably better supported by allowing `an {X}` or `a {X}` as variable names, so you could say

```
An illusion is lies

If your love is an illusion
...
```

`Forever` we'll reserve in case we need a rock'n'roll alias for `Infinity` when dividing by zero.
