### ISSUE TITLE
Operator comparison (greater than or equal to)

### ISSUE THREAD

**Issue by drewajp** [dylanbeattie/rockstar#20]
The only way that the fizzbuzz example works is if the line "While your heart is higher than your soul" is logically "while (your heart >= your soul)" yet comparative operators are described as being < and >

**Comment by ashellwig** [comment]
It does say “higher than” not “higher than or at” so I’m not sure where the issue is with using the `< >` operators. Perhaps something else like `while your heart is higher or at your soul` would work but I’m not sure if  `or` works as a keyword.

**Comment by drewajp** [comment]
@ashellwig It's not a problem that the `< >` operators are used, it's just that the example code doesn't work unless `>=` is used (unless I'm not reading it right) so I was inquiring about using those operators.

**Comment by peteri** [comment]
Or we could add an extra build your heart up line.
