### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by alexandremj** [dylanbeattie/rockstar#32]
There probably should be a way to comment code, either to clarify blocks or allow better metric within the lyrics without compromising previously written code

The first use is meant for actual use of the language on real-world code, which isn't probably going to happen and so isn't as important

For the second use, maybe make the compiler ignore lines without any language keywords (I'm not sure if this is doable, don't know much about compilers).

**Comment by moreheadm** [comment]
The README seems to suggest that comments are anything within parentheses (see the examples) but it should probably clarify this.

**Comment by dylanbeattie** [comment]
Yeah, anything in parentheses is a comment. Doc update incoming.

**Comment by dylanbeattie** [comment]
https://github.com/dylanbeattie/rockstar/issues/32

**Comment by ep12** [comment]
That would conflict with the idea of async code in () #30 maybe a keyword like rem in BASIC and windows cmd, but more rockstar-like? # or //or even ; would be ugly...

**Comment by gpetters94** [comment]
What about multiline comments? Something like
```
(CHORUS)
Comment goes here
(VERSE)
```
would probably fit in with the lyrics-sheet aesthetic.
