### ISSUE TITLE
Loop problems

### ISSUE THREAD

**Issue by palfrey** [dylanbeattie/rockstar#4]
Loop examples included in the README:
```
Tommy was a dancer
While Tommy ain't nothing
Shout it
Knock it down
And around we go
```
and
```
Modulus takes Number and Divisor
While Number is higher than Divisor
Take Divisor from Number
Give back Number
````

Couple of problems:
* `Around we go` appears to be the "multi-line loop" statement, but that's not documented.
* There's no indication about whether a while loop is multi-line or one block. So, the first example above just has two blocks, as the `And around we go` is one block with `Knock it down` but `Shout it` is also another block. OTOH the second example has no `Around we go` but seems to just implicitly treat the `Take Divisor from Number` as a single-block while loop?

Thoughts?

**Comment by ep12** [comment]
`Give back Number` seems to be the end of the function definition. This is great to force developers to return something. Some bugs come from ifs without else, so this would make those bugs very rare.
I guess `Around we go` is the end of a block like }, end or similar. This would mean that loops are block statements. This is great for the compatibility with python. I think it could be possible to write a performance-focussed tokeniser and lexer that uses python's AST module for fast interpreted rockstar execution.

**Comment by wolfgang42** [comment]
There seems to be a lot of confusion around how blocks work, and different types of code blocks seem to have completely different syntaxes.

* For functions:
  > A blank line denotes the end of a function body. 
  > Functions in Rockstar always have a return value, indicated by the Give back keyword.

* For loops, the docs don't say explicitly but `around we go` and `end` appear to end a block. However, the Modulus/Midnight function in the example doesn't have either, so I guess the `give back`/end of function terminate the loop?

* Conditionals appear to require `And` before subsequent statements to keep them in the block. This isn't documented, but the TODO section says:
   > I'm not sold on the idea of continuation prefixes for block syntax - for starters it won't let you implement nested blocks.

**Comment by young-steveo** [comment]
From what I can tell it now looks like `\n\n` ends blocks and functions, and `Around we go` has been removed, so dies this resolve this issue?

**Comment by cwfitzgerald** [comment]
I would agree. +1 to closing this.

**Comment by palfrey** [comment]
Agreed
