### ISSUE TITLE
Do commas have a syntactical meaning?

### ISSUE THREAD

**Issue by wolfgang42** [dylanbeattie/rockstar#40]
Some of the example loops have a comma at the end of them:

```
Tommy was a dancer
While Tommy ain't nothing,
Knock Tommy down
```

but others don't:
```
Tommy was a dancer
While Tommy ain't nothing
Shout it
Knock it down

```

Are these commas supposed to be here? If they are, do they do anything or are they just ignored?

**Comment by N-Masi** [comment]
I don't believe they have any meaning in that example, though they do when you are calling a method (such as in his example ```Multiplication taking 3, 5```) in order to separate the different parameters being passed through. Because there's no documented use for commas in the example you gave above I would assume they were put in that specific example for lyrical purposes.

**Comment by erikcorry** [comment]
I don't want to appear a wuss, but that means the lexer needs to know whether we are calling a function.  My current solution is to special case commas at the end of a line.

More generally I'm currently ignoring other punctuation like question marks and exclamation marks, which feels like the right thing to do.  Commas are the odd ones out here, cramping the poet's style.

It would be nice to find a different syntax to separate function arguments to free up commas to be used for artistic license.

**Comment by erikcorry** [comment]
Thinking about this a bit more I think perhaps the lexer can just ignore commas completely.  The expression syntax seems constrained enough that you always know when you are done with the previous argument and it's time to start the next.  I'm going to see if I can get that to work.

**Comment by yanorestes** [comment]
rockstar-py ignore all trailing commas. It'd be nice to get a list of characters that could go on the end of a line, so we could ignore it all.

**Comment by dylanbeattie** [comment]
Commas are currently necessary in function calls because if they weren't, you'd get this edge case

```
Function takes X and Y

Black is 1
Black Betty is 2
Boop is 3
Betty Boop is 4

Function Black, Betty Boop (unambiguous)
Function Black Betty, Boop (unambiguous)
Function Black Betty Boop (currently undefined)
```

This could be addressed by clarifying whether the variable name parser is greedy or not, but we'd need to resolve this and any other edge cases before we could eliminate the use of commas in function argument lists.

**Comment by erikcorry** [comment]
OK, my variable parser is certainly greedy so this doesn't currently arise for me.

**Comment by wolfgang42** [comment]
That is ambiguous with the boolean and operator--i. e. does `Modulus taking Counter and Fizz` mean `Modulus(Counter && Fizz)` or `Modulus(Counter, Fizz)`?

**Comment by wolfgang42** [comment]
They haven't been specced yet, but they definitely exist in the language--the fizzbuzz examples are already using them.

**Comment by wrenoud** [comment]
Ah! I kept scouring the docs...

**Comment by wolfgang42** [comment]
Just made an issue that they should be added: #101.

**Comment by erikcorry** [comment]
The parser at https://github.com/erikcorry/rockstar now parses all of fizz buzz and ignores all commas.  Also ignores the word "baby" and exclamation marks, question marks, etc.  Newlines are significant in several places.
