### ISSUE TITLE
Allow actions before conditional

### ISSUE THREAD

**Issue by vcanaa** [dylanbeattie/rockstar#42]
That makes it possible to have something like this

My Life is nothing without you

Equivalent of
If not you then 
My life is nothing

**Comment by dylanbeattie** [comment]
Nice idea, but as of https://github.com/dylanbeattie/rockstar/commit/d46d62651593c60b996dc52fd20718742a6d7ecd `without` is now used as an alias for `minus` for arithmetic. 

```
My life is nothing without your love
```

would initialise the variable `my life` to be 0 - the value of `your love`

**Comment by vcanaa** [comment]
My example was unfortunate, let me use the correct conditional.
I wanted to be able to write this:
My life is nothing if you are not here

Instead of:
If you are not here, my life is nothing

For musicality sake
