### ISSUE TITLE
Any restrictions for file extension?

### ISSUE THREAD

**Issue by povils** [dylanbeattie/rockstar#44]
Do we have any restrictions on file extension to indicate it is rockstar language? Like: .rock, .lyrics, .song or something else.

**Comment by NickHooked** [comment]
I like the .lyrics extension!

**Comment by povils** [comment]
Would it make sense to run script like :smile: 
`rockstar .lyrics`

**Comment by supersmola** [comment]
*.rnr

**Comment by jaysonesmith** [comment]
I'm down for .rock or .lyrics personally

**Comment by vcanaa** [comment]
+1 for .rock

**Comment by yanorestes** [comment]
On the Python transpiler I used .rock and .rockstar as examples, but any extension is accepted. If restrictions are defined, I'll change it! ;)

**Comment by wolfgang42** [comment]
Rockstar-js is also using `.rock` currently.

**Comment by zeg-io** [comment]
.track

**Comment by dylanbeattie** [comment]
I'm going with `.rock` since it's obvious, short, and already in use by several implementations.

https://github.com/dylanbeattie/rockstar/commit/d7300d6502b72b150819dfb799128524e24bb313
