### ISSUE TITLE
Possibly conflicting examples in definition of single quote

### ISSUE THREAD

**Issue by nistur** [dylanbeattie/rockstar#45]
In the string literals section, a single quote is defined as being an a letter of the alphabet

> The single quote character in Rockstar is treated as a letter of the alphabet. This seems unusual until you remember that `I ain't talkin' 'bout love` is a perfectly valid rock'n'roll sentence.

However, later on in the Poetic Number Literals examples, there is this example

>`My dreams were ice. A life unfulfilled; wakin' everybody up, taking booze and pills` - initialises my dreams with the value 3.1415926535

Which would suggest that the single quote in `wakin'` is not counted as an alphabetical letter as the definition states

> Other than the first period, any non-alphabetical characters are ignored.

If this is intended, then it may be worth clarifying this

**Comment by Dentosal** [comment]
About quotes: #16

**Comment by dylanbeattie** [comment]
Good point.

So on the one hand, ignoring single quotes in poetic literals - e.g. use `wakin'` instead of `waking` - makes it easier to find words with the right number of letters. But you're right, this IS a violation of the current rules regarding single quote characters.

How about a rule that ONLY [A-Za-z] are counted when parsing a poetic literal, so you're free to use as much punctuation as you like without altering the meaning of the program?

**Comment by nistur** [comment]
I think what would be clearer is to not define a single quote as a letter of the alphabet. As I don't see that it has any meaning anywhere, it might be better to describe it as such.

In fact, I might add a separate section on the single quote entirely
> The single quote character is not used by Rockstar to denote a string or character literal as in many other languages. It can however be used within symbol names to abbeviate as syntactic sugar, keeping in mind that `I ain't talkin' 'bout love` is a perfectly valid rock'n'roll sentence. 

I would recommend suggesting that it is ignored, making `ain't` equivalent to `aint` as it makes the general rules more simple, but you could also suggest using it as a single character wildcard in symbols, so `about` would be equivalent to `'bout`, which means you'd then have to define less symbols, but you would have to have special cases to deal with the original issue still.

**Comment by dylanbeattie** [comment]
OK, so there's a strong case for just stripping the single quote completely. I'd been playing with the idea of allowing contractions in assignments, so

`Janie's got a gun` 

would initialise `Janie` with the value `313`

But if the compiler ignores single quotes, this would end up as

`Janies got a gun`

which isn't syntactically valid.

BUT we could address this with a rule that says (expressed as transformation pseudocode)

1. `'s ` > ` is `
2. `'` > `<empty string>`

after which there are no single quotes left. This means that `ain't` and `aint` will be equivalent as identifiers, but I think we can live with that.

**Comment by dylanbeattie** [comment]
New rules:

https://github.com/dylanbeattie/rockstar/commit/1dce3ac417835ba4eebddbd59cc0014665b7cb5b

Given Rockstar's intriguing ancestral mixture of computer programming, creative English and idiomatic rock'n'roll, the single quote character presents all sorts of challenges.

Most programming languages use the single quote for quoting literal strings - `'like this'`. English, when written using the basic ASCII character set, often uses the single quote to stand in for the apostrophe to denote contractions or possessives - `you're, she's, he's, shouldn't, rock'n'roll`. Rock'n'roll uses the apostrophe apparently at random - `sweet child o' mine`, `ain't talkin' 'bout love`, `guns n' roses`.

Given three such dramatically diffeHere's how Rockstar interprets single quotes.

1. The sequence `'s\W+` - a single quote followed by a lowercase 's' and one or more whitespace characters - should be replaced with ` is ` (space, is, space) 
 * This allows `Janie's got a gun` (initialises `Janie` with the value `313`) and `Union's been on strike` (initialise `Union` with the value `426`) as valid variable declarations.  

2. All other single quotes are then ignored. `ain't` is equivalent to `aint`, `wakin'` has five letters, and `'''''` is equal to the empty string. This means you can use single quotes freely throughout your program to punctuate, adjust word lengths and generally channel the spirit of rock'n'roll without worrying about compiler errors.

**Comment by wolfgang42** [comment]
@dylanbeattie So the compiler/interpreter is expected to do a string replace on the source code before parsing, or is this expected to be done in the parser? IOW, what is the result of these expressions?

```
Johnny says he's got a gun
Henry is a girl's dream
Put "foo'n'bar" into Mary
```

With a naïve string replace, you get
```
Johnny says he's got a gun ("he is got a gun")
Henry is a girl's dream (1425)
Put "foo'n'bar" into Mary ("foonbar")
```
which doesn't seem right. On the other hand if `'s` replacement only applies to assignments then it makes more sense to specify that <code><var>Variable</var>'s</code> is equivalent to <code><var>Variable</var> is</code> and then clarify the rules around poetic literals, variable names, and `ain't`. (Is there anywhere else that single quotes would need to go?)
