### ISSUE TITLE
Single letter variable names

### ISSUE THREAD

**Issue by ep12** [dylanbeattie/rockstar#5]
The specification doesn't say whether "A" would be a proper variable name. It does start with an uppercase letter but that's all. It might be useful for short names like the i counter variable but I'm not sure if that fits with the aim of rockstar...

**Comment by dylanbeattie** [comment]
There's a strong case for allowing `a` and `an` as variable name PREFIXES, so I think we'll go with this approach. So `A` is not a valid variable name, but YOU can say something like:

`A storm was brewing down in Mississippi`

which would declare the variable `a storm` and initialise it with the value 7421.
