### ISSUE TITLE
Doc confusion

### ISSUE THREAD

**Issue by suuuehgi** [dylanbeattie/rockstar#6]
> Proper variables are proper nouns - any word that isn't a reserved keyword and _starts with an uppercase letter_. Proper variable names can contain spaces _as long as each space is followed by an uppercase letter_. 

> `Put 'Hello World' into the message` will assign the value `'Hello World'` to the variable `the message`.

as well as

> `My heart is true` - initialises the variable `my heart` with the Boolean value `true`

and many others.

How is this valid?

**Comment by ep12** [comment]
My, is and true are keywords, that's fine. The parser will find the keyword is, end the global variable declaration beginning with My and expecting a value. The value is the keyword true, with that the statement ends

**Comment by mflodin** [comment]
In that case it should be clarified that you don't always need to have each word in the variable name start with an uppercase letter.

**Comment by peteri** [comment]
You need capitals for proper variables, common variables start with my etc and start with lower case.

**Comment by dylanbeattie** [comment]
Common variables MUST start with `a`, `an`, `the`, `my` or `your` followed by a unique variable name, which must contain only lowercase ASCII letters a-z. So `my red house` would not be a valid variable name, but `my house` is fine.

Proper variables must always be a series of Title Cased Identifiers that aren't language keywords.

But remember I'm still sort of batting ideas around and seeing how they work so all this is (a) just for fun, (b) subject to change and (c) getting WAAAY more issues and PRs than I thought I would. Which is kinda cool. :)
