### ISSUE TITLE
Waits 

### ISSUE THREAD

**Issue by RichardC99** [dylanbeattie/rockstar#70]
### Wait

Waits are instantiated by calling Solo, there are 2 types of Wait Guitar and Drum 

Guitar = Wait. 
Example Guitar.Solo(4 Bar) = a 4 second wait, this can be made conditional to a lyric allowing the solo to be ended early.
Drum = Sleep. 
Example Drum.Solo(4 Bar) = a 4 second sleep. Sensible Rockstar coding standards indicate that Drum.Solo should be used sparingly and where possible not at all. 

Rockstar adds an inherent random element to the Solo method ensuring the length of time could be some magnitude longer then planned. It is never shorter.

**Comment by dylanbeattie** [comment]
It's a cool idea, but doesn't work for actually writing lyrics - I've seen maybe a handful of liner notes and record sleeves that call out the solos, but the whole point of Rockstar is that the programs you write should also be vaguely plausible as cheesy rock lyrics.

The idea of solos as waits/interludes might have some mileage but I'm gonna close this one for now.
