### ISSUE TITLE
Allow lines starting with `(` to end blocks/functions

### ISSUE THREAD

**Issue by cowboy** [dylanbeattie/rockstar#71]
Like the following:

```Midnight takes your heart and your soul
While your heart is as high as your soul
Put your heart without your soul into your heart
(Into your heart)
Give back your heart
(Give back your heart)
(Give back your heart)
Desire is a lovestruck ladykiller
My world is nothing 
Fire is ice
Hate is water
Until my world is Desire,
Build my world up
If Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing
Shout "FizzBuzz!"
Take it to the top
(To the top)
If Midnight taking my world, Fire is nothing
Shout "Fizz!"
Take it to the top
(To the top)
If Midnight taking my world, Hate is nothing
Say "Buzz!"
Take it to the top
(To the top)
Whisper my world```

**Comment by wolfgang42** [comment]
Is there a reason you think this won't work now? My reading of the spec is that variables are completely ignored, so I would expect this to work already unless I've misinterpreted something.

**Comment by yanorestes** [comment]
It's not explicitly defined, it won't work on my Python transpiler, for example. Rockstar comments are directly converted into Python comments, and the blank lines control the identation (in Python, the identaton specifies the block the code is working with, instead of {}).

**Comment by cowboy** [comment]
It's my understanding that, from the readme, Blocks are "terminated by a blank line or the end-of-file" and for Functions, "A blank line denotes the end of a function body." I didn't see anything that suggests we can use lines beginning with `(` there.

**Comment by cwfitzgerald** [comment]
In theory, a line with a comment on it is a blank line. There's no reason this really wouldn't work. It does with my up and coming compiler, but I had to make sure specifically that it worked.

**Comment by cowboy** [comment]
Sorry, I totally missed the fact that `()` delimit comments. I don't think it makes sense for lines surrounded by `()` to also function as end-of-block and end-of-body markers. Bummer!

I generally like the idea, but I'm going to close this issue as "RTFM"

**Comment by yanorestes** [comment]
I think we'll be better off if this gets cleared specified by @dylanbeattie
