### ISSUE TITLE
Switch `of` and `by`?

### ISSUE THREAD

**Issue by OhadRau** [dylanbeattie/rockstar#72]
Intuitively, you would expect the opposite behavior. E.g. `1 of 2` = 1/2, while `2 by 4` = 8. Both are sometimes used in English, so I think it would make sense to reverse the order of these two keywords.

**Comment by 3geek14** [comment]
"One half of six slices of pizza is three slices of pizza."

"Two (groups) of four flowers is eight flowers."

I don't have strong opinions on 'by', but I agree with the current specification when it comes to the meaning of 'of'.

**Comment by dylanbeattie** [comment]
Yeah, agreed - `by` is potentially confusing. I think `of` works just fine by `by` as an alias for `over` is (a) misleading, and (b) maybe a bit unnecessary given `over` is already pretty colloquial.

**Comment by dylanbeattie** [comment]
`by` removed in https://github.com/dylanbeattie/rockstar/commit/bc43323992450850692af8ca10772a1c349822e3
