### ISSUE TITLE
Clarify Common Variable Identity

### ISSUE THREAD

**Issue by cwfitzgerald** [dylanbeattie/rockstar#85]
The question boils down to:

Is `my love` the same variable as `your love`?

Though I would say that they aren't, it isn't abundantly clear from the spec.

**Comment by yanorestes** [comment]
They are not. The prefixes "my" or "your" are part of the variable name.

**Comment by wolfgang42** [comment]
This should probably be reopened as this still needs to be clarified in the spec.
